name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update APT
      run: sudo apt update

    - name: Install SDL2
      run: sudo apt install -y libsdl2-dev
      
    - name: Install GLEW
      run: sudo apt install -y libglew-dev

    - name: Install Vulkan SDK
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        sudo apt update
        sudo apt install -y vulkan-sdk

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build (OpenGL)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target fresa-opengl

    - name: Build (Vulkan)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target fresa-vulkan

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Store Binary (OpenGL)
      uses: actions/upload-artifact@v2
      with:
        name: fresa-opengl-linux
        path: bin/opengl/*

    - name: Store Binary (Vulkan)
      uses: actions/upload-artifact@v2
      with:
        name: fresa-vulkan-linux
        path: bin/vulkan/*